id: P009204
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:27:55.598426
source_metadata:
  id: bdr:W1KG12660
  title: དྲི་མེད་ཤེལ་ཕྲེང་ནས་བཤད་པའི་སྨན་གྱི་འཁྲུངས་དཔེ་མཛེས་མཚར་མིག་རྒྱན།
  author: ''
  volumes:
    d2b025672974470cac60219f37039d00:
      image_group_id: I1KG12685
      title: ''
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
